# Generated by Django 5.2.6 on 2025-11-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_page_tinymcemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='is_reviewed',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether media is reviewed, so it can appear on public listings'),
        ),
    ]
