# Generated by Django 5.2.6 on 2025-11-05 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_alter_media_is_reviewed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MediaCMS', help_text='站点名称', max_length=200)),
                ('site_description', models.TextField(default='开源媒体内容管理系统', help_text='站点描述')),
                ('site_keywords', models.CharField(default='视频,媒体,CMS', help_text='站点关键词', max_length=500)),
                ('allow_registration', models.BooleanField(default=True, help_text='允许用户注册')),
                ('require_approval', models.BooleanField(default=False, help_text='新用户需要审核')),
                ('enable_comments', models.BooleanField(default=True, help_text='允许评论')),
                ('moderate_comments', models.BooleanField(default=False, help_text='评论需要审核')),
                ('enable_ratings', models.BooleanField(default=True, help_text='允许评分')),
                ('enable_reporting', models.BooleanField(default=True, help_text='允许举报')),
                ('max_file_size', models.IntegerField(default=1024, help_text='最大文件大小(MB)')),
                ('allowed_video_formats', models.CharField(default='mp4,avi,mov,mkv,flv', help_text='允许的视频格式', max_length=200)),
                ('allowed_image_formats', models.CharField(default='jpg,jpeg,png,gif,webp', help_text='允许的图片格式', max_length=200)),
                ('allowed_audio_formats', models.CharField(default='mp3,wav,ogg,flac', help_text='允许的音频格式', max_length=200)),
                ('auto_encode', models.BooleanField(default=True, help_text='自动编码')),
                (
                    'default_quality',
                    models.CharField(choices=[('low', '低质量'), ('medium', '中等质量'), ('high', '高质量'), ('ultra', '超高质量')], default='medium', help_text='默认编码质量', max_length=20),
                ),
                ('generate_thumbnails', models.BooleanField(default=True, help_text='生成缩略图')),
                ('enable_captcha', models.BooleanField(default=False, help_text='启用验证码')),
                ('max_login_attempts', models.IntegerField(default=5, help_text='最大登录尝试次数')),
                ('lockout_duration', models.IntegerField(default=15, help_text='登录锁定时间(分钟)')),
                ('enable_moderation', models.BooleanField(default=True, help_text='启用内容审核')),
                ('enable_word_filter', models.BooleanField(default=True, help_text='敏感词过滤')),
                ('allowed_domains', models.TextField(default='http://localhost:5173\nhttp://localhost:5174', help_text='允许的域名(跨域),每行一个')),
                ('enable_email', models.BooleanField(default=False, help_text='启用邮件发送')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', help_text='SMTP服务器', max_length=200)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP端口')),
                ('from_email', models.EmailField(default='noreply@mediacms.io', help_text='发件人邮箱', max_length=254)),
                ('from_name', models.CharField(default='MediaCMS', help_text='发件人名称', max_length=100)),
                ('use_tls', models.BooleanField(default=True, help_text='使用TLS')),
                ('send_welcome_email', models.BooleanField(default=True, help_text='注册欢迎邮件')),
                ('send_comment_notification', models.BooleanField(default=True, help_text='评论通知邮件')),
                ('send_like_notification', models.BooleanField(default=False, help_text='点赞通知邮件')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='最后更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
            },
        ),
    ]
