# Generated by Django 5.2.6 on 2025-11-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='allow_anonymous_actions',
            field=models.CharField(default='report,like,dislike,watch', help_text='允许匿名用户的操作（逗号分隔）', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='allow_anonymous_user_listing',
            field=models.BooleanField(default=True, help_text='匿名用户可列出所有用户'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='allow_custom_media_urls',
            field=models.BooleanField(default=False, help_text='允许自定义媒体URL'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='allow_mention_in_comments',
            field=models.BooleanField(default=False, help_text='允许@提及用户'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='allow_video_trimmer',
            field=models.BooleanField(default=True, help_text='允许视频剪辑'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='calculate_md5sum',
            field=models.BooleanField(default=False, help_text='计算上传文件的MD5校验和'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='can_add_media',
            field=models.CharField(choices=[('all', '所有人'), ('email_verified', '已验证邮箱'), ('advancedUser', '高级用户')], default='all', help_text='谁可以上传媒体', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='can_comment',
            field=models.CharField(choices=[('all', '所有人'), ('email_verified', '已验证邮箱'), ('advancedUser', '高级用户')], default='all', help_text='谁可以评论', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='can_dislike_media',
            field=models.BooleanField(default=True, help_text='显示踩按钮'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='can_like_media',
            field=models.BooleanField(default=True, help_text='显示点赞按钮'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='can_report_media',
            field=models.BooleanField(default=True, help_text='显示举报按钮'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='can_see_members_page',
            field=models.CharField(choices=[('all', '所有人'), ('editors', '编辑'), ('admins', '管理员')], default='all', help_text='谁可以查看会员页面', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='can_share_media',
            field=models.BooleanField(default=True, help_text='显示分享按钮'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='cannot_add_media_message',
            field=models.TextField(default='User cannot add media, or maximum number of media uploads has been reached.', help_text='无法上传时的提示消息'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='chunkize_video_duration',
            field=models.IntegerField(default=300, help_text='视频分块时长（秒）'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_theme',
            field=models.CharField(choices=[('light', '亮色'), ('dark', '暗色')], default='light', help_text='默认主题', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='do_not_transcode_video',
            field=models.BooleanField(default=False, help_text='禁用视频转码（仅显示原始文件）'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='extra_css_paths',
            field=models.TextField(blank=True, default='', help_text='额外CSS文件路径（每行一个）'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ffmpeg_default_preset',
            field=models.CharField(
                choices=[
                    ('ultrafast', '极快'),
                    ('superfast', '超快'),
                    ('veryfast', '很快'),
                    ('faster', '较快'),
                    ('fast', '快'),
                    ('medium', '中等'),
                    ('slow', '慢'),
                    ('slower', '较慢'),
                    ('veryslow', '很慢'),
                ],
                default='medium',
                help_text='FFmpeg编码预设',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='generate_sitemap',
            field=models.BooleanField(default=False, help_text='生成站点地图'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='global_login_required',
            field=models.BooleanField(default=False, help_text='需要登录才能访问整个站点'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='language_code',
            field=models.CharField(
                choices=[
                    ('en', 'English'),
                    ('zh-hans', '简体中文'),
                    ('zh-hant', '繁体中文'),
                    ('ja', '日本語'),
                    ('ko', '한국어'),
                    ('es', 'Español'),
                    ('fr', 'Français'),
                    ('de', 'Deutsch'),
                    ('ru', 'Русский'),
                    ('ar', 'العربية'),
                ],
                default='zh-hans',
                help_text='默认语言',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='load_from_cdn',
            field=models.BooleanField(default=False, help_text='从CDN加载静态资源'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='login_allowed',
            field=models.BooleanField(default=True, help_text='显示登录按钮'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_chars_for_comment',
            field=models.IntegerField(default=10000, help_text='评论最大字符数'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_media_per_playlist',
            field=models.IntegerField(default=70, help_text='播放列表最大媒体数'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='minimum_resolutions_to_encode',
            field=models.CharField(default='144,240', help_text='最小编码分辨率（逗号分隔）', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='number_of_media_user_can_upload',
            field=models.IntegerField(default=100, help_text='用户最大上传媒体数量'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='portal_logo_dark_svg',
            field=models.CharField(default='/static/images/logo_dark.svg', help_text='暗色Logo SVG路径', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='portal_logo_light_svg',
            field=models.CharField(default='/static/images/logo_light.svg', help_text='亮色Logo SVG路径', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='portal_workflow',
            field=models.CharField(choices=[('public', '公开'), ('private', '私有'), ('unlisted', '不列出')], default='public', help_text='门户工作流模式', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='pre_upload_media_message',
            field=models.TextField(blank=True, default='', help_text='上传前提示消息'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='register_allowed',
            field=models.BooleanField(default=True, help_text='显示注册按钮'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='related_media_strategy',
            field=models.CharField(choices=[('content', '按内容'), ('author', '按作者')], default='content', help_text='相关媒体推荐策略', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='reported_times_threshold',
            field=models.IntegerField(default=10, help_text='举报多少次后自动设为私有'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='show_original_media',
            field=models.BooleanField(default=True, help_text='显示原始文件链接'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sidebar_footer_text',
            field=models.TextField(blank=True, default='', help_text='侧边栏页脚文本'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='slideshow_items',
            field=models.IntegerField(default=30, help_text='幻灯片展示图片数量'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sprite_num_secs',
            field=models.IntegerField(default=10, help_text='精灵图间隔（秒）'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='time_to_action_anonymous',
            field=models.IntegerField(default=600, help_text='匿名用户操作限制间隔（秒）'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='time_zone',
            field=models.CharField(default='Asia/Shanghai', help_text='系统时区', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='timestamp_in_timebar',
            field=models.BooleanField(default=False, help_text='时间戳评论显示在时间轴'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='upload_media_allowed',
            field=models.BooleanField(default=True, help_text='显示上传按钮'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='use_rounded_corners',
            field=models.BooleanField(default=True, help_text='使用圆角UI'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='users_needs_to_be_approved',
            field=models.BooleanField(default=False, help_text='新用户需要管理员批准'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='video_chunks_duration',
            field=models.IntegerField(default=240, help_text='每个分块持续时间（秒）'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='video_player_featured_video_on_index',
            field=models.BooleanField(default=False, help_text='首页显示特色视频播放器'),
        ),
    ]
